" ファイルエンコーディングをUTF-8に設定
set fenc=utf-8
" バックアップファイルを作成しない
set nobackup
" スワップファイルを作成しない
set noswapfile
" ファイルが外部で変更された場合に自動的に読み直す
set autoread
" コマンドを表示する
set showcmd
" 行番号を表示する
set number
" スマートインデントを有効にする
set smartindent
" タブをスペースに変換する
set expandtab
" タブ幅を2に設定
set tabstop=2
" インデント幅を2に設定
set shiftwidth=2
" 現在の行を強調表示
set cursorline
" 括弧入力時の対応する括弧を表示
set showmatch
" ステータスラインを常に表示
set laststatus=2
" 検索文字列入力時に順次対象文字列にヒットさせる
set incsearch
" 検索時に最後まで行ったら最初に戻る
set wrapscan
" 検索語をハイライト表示
set hlsearch
" ESC連打でハイライト解除
nmap <Esc><Esc> :nohlsearch<CR><Esc>
" インサートモードでjjを押すとESCに変換
inoremap <silent> jj <ESC>
" シンタックスハイライトを有効にする
syntax on
